name: Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    name: Build Extension
    runs-on: ubuntu-20.04
    container: ghcr.io/paulhatch/plgo:1.4.1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Version
        id: version
        uses: paulhatch/semantic-version@v4.0.2
      - name: Build Extension
        run: |
          plgo -x -v $VERSION -d "$(jq -r '.abstract' META.json)" .
        env:
          VERSION: ${{ steps.version.outputs.version }}
