name: Release
on: workflow_dispatch
jobs:
  build:
    name: Build Extension
    runs-on: ubuntu-20.04
    container: ghcr.io/paulhatch/plgo:1.4.3
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Version
        id: version
        uses: paulhatch/semantic-version@v4.0.2
      - name: Build Extension
        run: |
          plgo -x -v $VERSION -d "$(jq -r '.abstract' META.json)" .
          cat extension.sql >> ./build/konfigraf--${VERSION}.sql
          export FILES=$(echo -n $(ls ./build/*.sql) |  jq --raw-input --compact-output --slurp 'split(" ")')
          jq \
            --arg version $VERSION \
            --argjson files $FILES \
            '.version = $version | .provides.konfigraf.file = $files' \
            META.json >> ./build/META.json
        env:
          VERSION: ${{ steps.version.outputs.version }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: extension
          path: build
  release:
    name: Bundle and Publish
    runs-on: ubuntu-20.04
    container: pgxn/pgxn-tools
    needs: build
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: extension
      - name: Bundle
        run: pgxn-bundle
      - name: Release on PGXN
        run: pgxn-release
        env:
          PGXN_USERNAME: ${{ secrets.PGXN_USERNAME }}
          PGXN_PASSWORD: ${{ secrets.PGXN_PASSWORD }}
